services:
  - type: web
    name: nutri-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /
    autoDeploy: true
    plan: free
releaseCommand: python manage.py migrate