services:
  - type: web
    name: nutri-app
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: bash start.sh
    healthCheckPath: /healthz/
    autoDeployTrigger: commit
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: NUTRITIONIX_APP_ID
        sync: false
      - key: NUTRITIONIX_APP_KEY
        sync: false
